name = "EllipseGeometry"
uuid = "56405771-b37b-4c45-a787-cc0a2fd6b078"
authors = ["Oleg Soloviev <oleg.soloviev@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
